[[preface]]
[preface]
== 서문

파이썬은 간단하면서도 강력한, 몇 안되는 프로그래밍 언어들 중 하나일 것입니다.
파이썬은 초보자는 물론 숙련자에게도 잘 어울리지만, 가장 중요한 점은, 파이썬으로 프로그래밍 하는 것은 즐겁습니다.
이 책은 당신이 파이썬이라는 아름다운 프로그래밍 언어를 배우고,
당신이 하려는 일을 빠르고 쉽게 해결하는 방법을 보여드리는 것을 목적으로 작성되었습니다.

=== 이 책은 누가 읽으면 좋을까요?

이 책은 파이썬의 가이드 혹은 튜토리얼의 역할을 하도록 작성되었습니다.
프로그래밍에 대해 아무런 지식이 없는 '완전 초보자'들을 주 독자로 설정하였습니다.
물론 경험이 많은 프로그래머들에게도 유용한 책입니다.

이 책의 목표는 컴퓨터로 텍스트 문서를 저장하는 것밖에 모르는 사람도 이 책을 통해
파이썬을 배울 수 있도록 하는 것입니다. 물론 당신이 이전에 프로그래밍 경험이 있다고 하더라도,
이 책을 통해 파이썬을 익힐 수 있을 것입니다.

만약 당신이 프로그래밍 경험을 가지고 있다면, 아마도 당신은 당신이 가장 좋아하는 언어와 파이썬의
차이점에 관심을 갖게 될 것입니다. 저는 이 책에서 다른 언어와 파이썬과의 많은 차이점을 강조해 두었습니다.
작은 주의를 드리자면, 얼마 안 지나서 당신이 가장 좋아하는 언어는 파이썬이 될 것입니다!

[[history_lesson]]
=== History Lesson

제가 파이썬을 처음 시작하게 된 계기는 전에 작성했던 'Diamond' 라는 소프트웨어를 좀 더 쉽게 설치할
수 있게 하기 위해 그것의 설치 프로그램을 작성하려고 했던 일이었습니다. 당시에 Qt 라이브러리를
사용하고 싶었는데, 이를 위해 파이썬과 펄 중 하나를 골라야 했었지요. 그래서 인터넷을 찾아보았는데
유명한 해커 http://www.python.org/about/success/esr/[Eric S. Raymond 가 쓴 글]을 발견하게 되었습니다.
거기에는 파이썬이 어떻게 자신이 가장 좋아하는 프로그래밍 언어가 되었는지에 대해 적혀 있었지요.
또한 당시 Perl-Qt 바인딩에 비해 PyQt 바인딩이 좀 더 안정적이었기도 해서, 저는 파이썬을 선택하게
되었습니다.

다음으로 저는 좋은 파이썬 책이 있는지 찾아보기 시작했습니다. 그런데, 아무것도 찾을 수가 없었습니다!
몇 권의 오라일리(O'Reilly) 책을 찾았지만 이것들은 너무 비싸고 초보자를 위한 가이드이기보다는 레퍼런스
매뉴얼에 가까웠습니다. 그래서, 저는 파이썬 문서를 검색해보기 시작했습니다. 그렇지만 제가 찾은 것들은
너무 간략하거나 짧은 것들 뿐이었습니다. 저는 이런 문서들을 통해 기본적인 것들에 대한 도움을 받을 수
있었지만 파이썬에 대해 완전히 알 수는 없었습니다. 또 저는 프로그래밍을 전에 해 보았기 때문에 이런
짧은 문서들을 겨우겨우 이해해나갈 수 있었지만, 초보자에게는 불가능한 일이라는 것도 알게 되었습니다.

제가 파이썬을 처음 시작하고 6 개월정도 지난 뒤, 저는 레드햇 리눅스(Red Hat Linux) 9.0 을 설치하였는데
불현듯 KWord를 사용하여 파이썬에 대해 뭔가 적어보자는 생각이 떠올랐습니다. 처음에는 몇 장으로
시작했지만 곧 30 페이지 정도의 문서가 되었습니다. 그렇게 되니 좀 더 내용을 정리해서 책의 형태로
만들면 좀 더 유용하겠다는 생각을 했습니다. 그 후 _많은_ 재작성 끝에, 파이썬이라는 언어를 익히는
데 유용한 이 가이드를 만들 수 있었습니다. I consider
this book to be my contribution and tribute to the open source community.

This book started out as my personal notes on Python and I still consider it in the same way,
although I've taken a lot of effort to make it more palatable to others :)

In the true spirit of open source, I have received lots of constructive suggestions, criticisms and
<<who_reads_bop,feedback>> from enthusiastic readers which has helped me improve this book a lot.

=== Status Of The Book

- Latest update of this book was in Mar-Apr 2014, converted to
  http://asciidoctor.org/docs/what-is-asciidoc/[Asciidoc] using
  http://swaroopch.com/2013/10/17/emacs-configuration-tutorial/[Emacs 24] and
  https://github.com/sensorflo/adoc-mode/wiki[adoc-mode].
- In Dec 2008, the book was updated for the Python 3.0 release (one of the first books to do
  so). But now, I have converted the book back for Python 2 language because readers would often
  get confused between the default Python 2 installed on their systems vs. Python 3 which they had
  to separately install and all the tooling, esp. editors would assume Python 2 as well. I had a
  hard time justifying why I had to aggravate readers and make them go through all this when the
  fact is that they can learn either one and it would be just as useful. So, Python 2 it is.

The book needs the help of its readers such as yourselves to point out any parts of the book which
are not good, not comprehensible or are simply wrong. Please {contact}[write to the main author] or
the respective <<translations,translators>> with your comments and suggestions.

=== 공식 홈페이지

The official website of the book is {homepage} where you can read the whole book online, download
the latest versions of the book, {buy}[buy a printed hard copy] and also send me feedback.

=== 생각할 것들

[quote,C. A. R. Hoare]
__________________________________________________
There are two ways of constructing a software design: one way is to make it so simple that there
are obviously no deficiencies; the other is to make it so complicated that there are no obvious
deficiencies.
__________________________________________________

[quote,C. W. Wendte]
__________________________________________________
Success in life is a matter not so much of talent and opportunity as of concentration and
perseverance.
__________________________________________________
