== A Byte Of Python 한국어 번역(Korean Translation of A Byte of Python)

이 책의 원 저자는 Swaroop C H 입니다.
책의 영어 원문은 http://www.swaroopch.com/notes/python/[http://www.swaroopch.com/notes/python/] 에서 확인하실 수 있습니다.

이 책은 아직 번역 중입니다.
번역에 문제가 있거나 의견 주시려면 pjb7687@gmail.com 으로 메일 주시기 바랍니다.

- HTML 버전 읽기: http://byteofpython-korean.sourceforge.net/byte_of_python.html
- PDF 버전 읽기: http://byteofpython-korean.sourceforge.net/byte_of_python.pdf
 * 참고: PDF 버전에 사용된 본문용 서체는 http://www.kopus.org/[한국출판인회의]에서 공개한
   `KOPUB 돋움/바탕` 을 수정하여 사용하였으며, 고정폭 서체로는
   +http://dev.naver.com/projects/nanumfont/[나눔고딕코딩글꼴]+을 사용하였습니다.


Original author of this book is Swaroop C H.
The website of original book is http://swaroopch.com/notes/python/[http://swaroopch.com/notes/python/].

Jeongbin Park is translating the book in Korean.
If you find any error or want to give some comments, please notify me via pjb7687@gmail.com.

- Read HTML Version: http://byteofpython-korean.sourceforge.net/byte_of_python.html
- Read PDF Version: http://byteofpython-korean.sourceforge.net/byte_of_python.pdf
 * Notice: The (sans-)serif font used in PDF version of the book is +http://www.kopus.org/[KOPUB] Dotum/Batang+,
   modified to support several latin characters. Also 
   +http://dev.naver.com/projects/nanumfont/[Nanum Gothic Coding Font]+ is used for monospace texts
   (especially for Python codes).
   
== HTML 및 PDF 파일 제작

문법 강조를 위해 설치해야 하는 pygments.rb에 버그가 있기 때문에 윈도우상에서
작업이 어려우므로 일단은 리눅스상에서 작업하는 것이 좋습니다.

일단 다음과 같은 프로그램이 필요합니다.

1. Ruby
 - 설치가 되어있지 않을 경우 +$ sudo apt-get install ruby+ 혹은 +$ sudo yum install ruby+ 로 설치하시기 바랍니다.
 - Ruby Development Package가 필요합니다. +$ sudo apt-get install ruby-dev+ 혹은 +$ sudo yum install ruby-devel+ 로
 설치하시기 바랍니다.
2. pygments
 - 파이썬의 pip 혹은 easy_install을 이용하여 pygments 패키지를 설치합니다.
3. pygments.rb
 - 먼저 gcc가 설치되어 있어야 합니다. build-essential 패키지 등을 설치하세요.
 - +gem install pygments.rb --version "=0.5.0"+ 으로 구버전의 pygments.rb를 설치합니다
 (root 권한이 필요할 수 있습니다). 최신버전은 제대로 동작하지 않는 것 같습니다. 어차피
 실제 문법 강조는 python의 pygments 패키지가 담당하므로 이 패키지의 버전은 별 상관이 없습니다.
4. Java Development Kit
 - JDK가 필요합니다. 적절한 패키지 혹은 Sun 공식 홈페이지에서 내려받아 설치하세요.
5. Asciidoctor
 - +gem install asciidoctor+ 를 입력하여 설치합니다.
6. Git
 - Git이 필요합니다. http://git-scm.com/downloads 을 참고하셔서 내려받아 설치하세요.
 - 이제 +git clone https://github.com/pjb7687/byte_of_python+ 하셔서 이 책의 저장소를 내려 받으세요.
 이 때 주의할점은 상위 경로에 한글이 포함된 폴더가 있으면 안됩니다 (예: '바탕 화면'에 받으면 안됩니다).

+$ . commands.bash+ 혹은 +$ source commands.bash+ 를 입력한 후,
+$ make_html+ (HTML 제작) 혹은 +$ make_pdf+ (PDF 제작) 명령으로 원하는 출력물을 만듭니다.

PDF 파일을 처음으로 제작하려고 할 경우 자동으로 +fopub+이 설치되므로 좀 시간이 걸릴 수 있습니다.

== A Byte of Python

"A Byte of Python" is a free book on programming using the Python language. It serves as a tutorial
or guide to the Python language for a beginner audience. If all you know about computers is how to
save text files, then this is the book for you.

To understand the http://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc format], see the
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference].

To convert the book from AsciiDoc format to output formats (HTML, PDF, EPUB, etc.), see
https://github.com/swaroopch/byte_of_python/blob/master/commands.bash[commands.bash].

To understand the freedoms you have with this book, see
https://github.com/swaroopch/byte_of_python/blob/master/LICENSE.asciidoc[LICENSE.asciidoc].

To translate this book, https://help.github.com/articles/fork-a-repo[fork the repository].

For queries, http://swaroopch.com/contact/[contact the author].
