== A Byte Of Python 한국어 번역(Korean Translation of A Byte of Python)

이 책의 원 저자는 Swaroop C H 입니다.
책의 영어 원문은 http://www.swaroopch.com/notes/python/[http://www.swaroopch.com/notes/python/] 에서 확인하실 수 있습니다.

이 책은 아직 번역 중입니다.
번역에 문제가 있거나 의견 주시려면 pjb7687@gmail.com 으로 메일 주시기 바랍니다.

- HTML 버전 읽기: http://byteofpython-korean.sourceforge.net/byte_of_python.html
- PDF 버전 읽기: http://byteofpython-korean.sourceforge.net/byte_of_python.pdf

Original author of this book is Swaroop C H.
The website of original book is http://swaroopch.com/notes/python/[http://swaroopch.com/notes/python/].

Jeongbin Park is translating the book in Korean.
If you find any error or want to give some comments, please notify me via pjb7687@gmail.com.

== A Byte of Python

"A Byte of Python" is a free book on programming using the Python language. It serves as a tutorial
or guide to the Python language for a beginner audience. If all you know about computers is how to
save text files, then this is the book for you.

To understand the http://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc format], see the
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc Syntax Quick Reference].

To convert the book from AsciiDoc format to output formats (HTML, PDF, EPUB, etc.), see
https://github.com/swaroopch/byte_of_python/blob/master/commands.bash[commands.bash].

To understand the freedoms you have with this book, see
https://github.com/swaroopch/byte_of_python/blob/master/LICENSE.asciidoc[LICENSE.asciidoc].

To translate this book, https://help.github.com/articles/fork-a-repo[fork the repository].

For queries, http://swaroopch.com/contact/[contact the author].
