[[stdlib]]
=== 표준 라이브러리

파이썬 표준 라이브러리는 파이썬을 설치할 때 항상 함께 설치되는 많은 수의 유용한 모듈들을 말합니다.
파이썬 표준 라이브러리에 익숙해지면 이를 이용해 해결할 수 있는 많은 문제들을 좀 더 빠르고 쉽게
해결할 수 있습니다.

지금부터 표준 라이브러리에 포함된 많은 모듈 중에서 자주 사용되는 몇가지 모듈에 대해 알아볼 것입니다.
파이썬 표준 라이브러리에 포함된 모든 모듈에 대한 자세한 설명은 파이썬과 함께 설치되는 설명서의
http://docs.python.org/2/library/['라이브러리 레퍼런스' 섹션] 에서 확인해 보실 수 있습니다.

여기서는 유용한 몇 개의 모듈만 다뤄 보겠습니다.

CAUTION: 이 장에서 다루는 내용은 조금 어려울 수 있습니다. 그런 경우 일단 이 장을 읽지 말고 넘기세요.
그렇지만 여러분이 파이썬에 좀 더 익숙해지게 되면 이 장으로 다시 돌아오기를 강력히 권합니다.

=== +sys+ 모듈

`sys` 모듈은 시스템의 기능을 다루는 함수들이 담겨 있습니다. We have already seen that the `sys.argv`
list contains the command-line arguments.

Suppose we want to check the version of the Python software being used, the `sys` module gives us
that information.

--------------------------------------------------
$ python
>>> import sys
>>> sys.version_info
sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
>>> sys.version_info.major == 2
True
--------------------------------------------------

.How It Works

The `sys` module has a `version_info` tuple that gives us the version information. The first entry
is the major version. We can pull out this information to use it.

[[logging]]
=== logging module

What if you wanted to have some debugging messages or important messages to be stored somewhere so
that you can check whether your program has been running as you would expect it? How do you "store
somewhere" these messages? This can be achieved using the `logging` module.

Save as `stdlib_logging.py`:

[source,python]
--------------------------------------------------
include::programs/stdlib_logging.py[]
--------------------------------------------------

Output:

--------------------------------------------------
include::programs/stdlib_logging.txt[]
--------------------------------------------------

If you do not have the `cat` command, then you can just open the `test.log` file in a text editor.

.How It Works

We use three modules from the standard library - the `os` module for interacting with the operating
system, the `platform` module for information about the platform i.e. the operating system and the
`logging` module to *log* information.

First, we check which operating system we are using by checking the string returned by
`platform.platform()` (for more information, see `import platform; help(platform)`). If it is
Windows, we figure out the home drive, the home folder and the filename where we want to store the
information. Putting these three parts together, we get the full location of the file. For other
platforms, we need to know just the home folder of the user and we get the full location of the
file.

We use the `os.path.join()` function to put these three parts of the location together. The reason
to use a special function rather than just adding the strings together is because this function
will ensure the full location matches the format expected by the operating system.

We configure the `logging` module to write all the messages in a particular format to the file we
have specified.

Finally, we can put messages that are either meant for debugging, information, warning or even
critical messages. Once the program has run, we can check this file and we will know what happened
in the program, even though no information was displayed to the user running the program.

[[motw]]
=== Module of the Week Series

There is much more to be explored in the standard library such as
http://docs.python.org/2/library/pdb.html[debugging],
http://docs.python.org/2/library/argparse.html[handling command line options],
http://docs.python.org/2/library/re.html[regular expressions] and so
on.

The best way to further explore the standard library is to read Doug Hellmann's excellent
http://pymotw.com/2/contents.html[Python Module of the Week] series (also available as a
http://amzn.com/0321767349[book]) and reading the http://docs.python.org/2/[Python documentation].

=== Summary

We have explored some of the functionality of many modules in the Python Standard Library. It is
highly recommended to browse through the http://docs.python.org/2/library/[Python Standard Library
documentation] to get an idea of all the modules that are available.

Next, we will cover various aspects of Python that will make our tour of Python more _complete_.
